# https://taskfile.dev

version: '3'

includes:
  build: ./taskfiles/build_{{OS}}.yml

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a
    silent: true

  all:
    desc: Run all tasks (build + install go, python, etc)
    cmds:
      - task: build:go
      - task: build:goimports
      - task: build:nvim
      - task: build:python3.10
    silent: true

  lite:
    desc: Run all tasks but, skip build + install of go, python (assumes already installed)
    cmds:
      - task: build:goimports
    silent: true

