# https://taskfile.dev

version: '3'

includes:
  build: ./taskfiles/build.yml

tasks:

  full:
    desc: Run all tasks (build + install go, python, etc)
    cmds:
      - task: build:starship-prompt
      - task: build:direnv
      - task: build:go:install
      - task: build:lazygit
      - task: build:goimports
      - task: build:nvim:install
      - task: build:python:install
      - task: build:rust:install
      - task: link 
    silent: true

  lite:
    desc: Run all tasks but, skip build + install of go, python (assumes already installed)
    cmds:
      - task: build:starship-prompt
      - task: build:direnv
      - task: link 
    silent: true

  link:
    desc: Links the items in this directory to their corresponding $HOME locations
    cmds:
      - task build:go:link
      - task build:nvim:link
      - ./scripts/link_items.sh
    silent: true
