# https://taskfile.dev

version: '3'

includes:
  build: ./taskfiles/build_{{OS}}.yml

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a
    silent: true

  all:
    desc: Run all tasks (build + install go, python, etc)
    cmds:
      - task: build:go
      - task: build:goimports
      - task: build:nvim-0.9.5
      - task: build:python3.10
      - task: build:rust
      - task: build:zellij
      - task: link 
    silent: true

  lite:
    desc: Run all tasks but, skip build + install of go, python (assumes already installed)
    cmds:
      - task: build:goimports
      - task: build:zellij
      - task: link 
    silent: true

  link:
    desc: Links the items in this directory to their corresponding $HOME locations
    cmds:
      - ./scripts/link_items.sh
    silent: true
