# https://taskfile.dev

version: '3'

includes:
  build: ./Taskfile_{{OS}}.yml

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a
    silent: true

  all:
    desc: Run all tasks
    cmds:
      - task: build:go
      - task: build:goimports
      - task: build:python3.10
    silent: true
